### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [sensehawk/qgis_plugin#1]
# Problem

Please fix the metadata.txt issue tracker from https://app.clickup.com/login to https://github.com/sensehawk/qgis_plugin/issues

**Comment by kirnh** [comment]
@NyakudyaA this has been fixed in version 1.1, please review said version for approval.

**Comment by kirnh** [comment]
@NyakudyaA can you please review and approve version 1.2 of the plugin? Thanks.

**Comment by kirnh** [comment]
1.2 version is approved. Closing this issue.

**Comment by kirnh** [comment]
@NyakudyaA please review and approve version 1.3. Thank you for your contribution.

**Comment by NyakudyaA** [comment]
@kirnh You do not need to ping me each time you upload a new version. I automatically get notifications when new plugins are uploaded and I will always try to review them at my earliest convenience
